# Generated by Django 5.2.14 on 2026-05-19 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('command', models.TextField()),
                ('working_dir', models.TextField()),
                ('pid', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
