# Generated by Django 5.2.14 on 2026-06-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='service',
            name='order',
            field=models.IntegerField(default=0, help_text='Urutan tampilan'),
        ),
        migrations.AddField(
            model_name='service',
            name='port',
            field=models.CharField(blank=True, help_text='Port atau URL (opsional)', max_length=50, null=True),
        ),
    ]
