# Generated by Django 5.2.14 on 2026-06-02 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_service_options_service_order_service_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='log_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
